### PR TITLE
Ownership for gredwitch turret base

### PR DESCRIPTION
**Pull request by plally**
set the owner of Hull and Yaw entities to the owner their parent (the turret entity)

relies on [cfc_waiter](https://github.com/cfc-servers/cfc_waiter)

### CODE REVIEW

**Comment by sarahsturgeon** [comment]
@PLally How did you test to confirm this works?

**Comment by plally** [comment]
spawned most of the emplacements and looked at their owner

**Comment by sarahsturgeon** [comment]
And just to confirm, this means that if someone kills another with the emplacements that the damage and kills will be attributed to them?

**Comment by plally** [comment]
Not sure, the turret part of the emplacement was already owned by the player. The main purpose of this was to allow players to interact with their emplacements with a physgun/toolgun without giving everyone permissions to interact with world.

**Comment by sarahsturgeon** [comment]
Okay, let's get this merged and we'll do independent testing of how Gredwitch interacts with the PvP addon.

**Review by sarahsturgeon — CHANGES_REQUESTED** [review]
In terms of idiomatic Lua, I think it's typical to name your server files as such: `sv_base_owner.lua` or something like that. What do you think about renaming this file?

**Comment by plally** [comment]
sv_gredwitch_owner or maybe sv_ownership?

i will go ahead and rename the other file as well.

**Comment by sarahsturgeon** [comment]
Whatever you think is best!

**Comment by plally** [comment]
ill go ahead and merge this if there are no other issues?

**Pull request merged**
